### ISSUE TITLE
Link port connection

### ISSUE THREAD

**Issue by JayCanuck** [Gameboypi/SPW#12]
Any chance of updating the board gerber files so the usb solder pads extend to pins on the link connector port?  While I like the idea of optionally putting a microUSB port (like mentioned in https://github.com/Gameboypi/SPW/issues/7), rather than a dummy GBA link port, it would be neat to add the 4 USB connections onto the link port itself as well. That way, we could make custom GBA accessories  or whatnot, rather that it being unconnected.

**Comment by Gameboypi** [comment]
Sorry! not possible for some reasons.. you can use magnet wire

**Comment by JayCanuck** [comment]
Odd, will do.
