### ISSUE TITLE
Ground/battery -

### ISSUE THREAD

**Issue by TobyDude** [Gameboypi/SPW#15]
Hi,
I had a small question? How is the pi connected to ground, I can't seem to find a point to which
the pi is connected. 

Thanks in advance.
Toby

**Comment by BRaSSaS** [comment]
It's connected trow pin 6, 9, 25 and 39.
If you look closely at the raspberry pinout scheme, and the spw circuit you will see that all the rpi ground are being used

**Comment by TobyDude** [comment]
Thanks for the quick response, But where does the battery – go to on the pi or does that connect to one of the ground pins?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by BRaSSaS** [comment]
I do not understand the question, the battery is connected to the battery connector/termina in case you use an original gameboy battery, or if you use another 3.7v generic battery, you will have to connect it to the TP4056 CHARGER (B+/-) or reuse the battery connector pads.

**Comment by TobyDude** [comment]
So then the pi receives power from out+ and out- on the tp4056. But where does out- connect to the pi?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BRaSSaS** [comment]
Same answer, to the pin 6, 9, 25, 30, 34 and 39. It's a ground, it's general ground.

**Comment by TobyDude** [comment]
Alright thanks man. 😃

Get Outlook for iOS<https://aka.ms/o0ukef>
