### ISSUE TITLE
Board shortcuts on pre-made image

### ISSUE THREAD

**Issue by julenvitoria** [Gameboypi/SPW#19]
Hi! I would like to know if in the premade image the combos that up and down the volume only work within retroarch or work in the whole system. If that combos works only within retroarch it could be any possibility of make it in the entire system?

Regards

**Comment by Gameboypi** [comment]
I've tested it on most emulators that’s raspberry pi zero can handle it, it’s just works fine unless you mean on the retropie menu? No it’s not working there
