### ISSUE TITLE
Eagle Files and button placement for X Y buttons?

### ISSUE THREAD

**Issue by freeacount1** [Gameboypi/SPW#2]
Hi, is there any chance you can upload the Eagle files? I would like to edit the pcb for DPI LCD output if possible thank you.

**Comment by woozer** [comment]
I would add a charger (booster) protection circuit and onboard I2S audio, although this solution is perfect for people less experienced with soldering!

DPI output would only be possible if you plan to use e.g. a Atmega32U4 for button input, and are OK to lose I2S sound, unless you add some USB audio (CM102 + FE1.1s).

Button presses could also be handled by an I2C IO expander connected to the cam port, with a device overlay like done on https://othermod.com/ 

W

**Comment by freeacount1** [comment]
I don't mind if I lose the I2S sound, I was going to add a USB hub along with a USB soundcard/pam8302 and MCP23017 for I2C controls.

as for the battery and boost feature i was gonna use GreatScott's  circuit

https://www.youtube.com/watch?v=Fj0XuYiE7HU

https://easyeda.com/GreatScott/LiPoChargeProtectBoost_copy-3d9f4c3ddc7347d7861776340b9b90b7

**Comment by woozer** [comment]
> If you could provide the eagle files for the SP board you designed I would like to give it a try.

That's not up to me! ;)

BTW, the cm102s+ USB audio chip is supposed to support up to 3 watts to a direct speaker connection, so you won't really need an amplifier.

W

**Comment by Gameboypi** [comment]
Sorry guys I can’t share my Eagle board files! :(
