### ISSUE TITLE
Kapton tape below the pi

### ISSUE THREAD

**Issue by Jonasbeavis** [Gameboypi/SPW#22]
Hi , loved your build and work , really impressive indeed! Need to ask if you put some Kapton tape below the raspberry pi zero before bound it/soldering to the PCB. Thx

**Comment by Gameboypi** [comment]
Thanks dude
I’m glad you liked it!
No need for kapton tape I already covered the vias with solder mask and there’s nothing under the raspberry pi except 2 holes for usb
