### ISSUE TITLE
Wrong charging module

### ISSUE THREAD

**Issue by LoBelly26** [Gameboypi/SPW#23]
Good morning everyone,
I think I bought a wrong tp4056, because it doesn't have the out+ and the out- on the board. It has anyway the Bat+, the Bat-, the In+, the In- and it also has the microUSB port. Can I use it anyway? What would this entail? Thank to everyone who will answer my question! (Sorry for my bad English)

**Comment by BRaSSaS** [comment]
Could you post some image or url with exact model that you use?
It is possible that the circuit you are referring to only makes the charge of the battery and the usb only for the output. They are circuits that are used only to build portable batteries / powerbanks. In that case it will not work, here the usb is used to charge the battery and the voltage output goes through the pins out +/-
