### ISSUE TITLE
ADS 1115/1015 install squematic

### ISSUE THREAD

**Issue by Jonasbeavis** [Gameboypi/SPW#26]
Hi , any chance to make some instructions how to install ADS ? Many thx

**Comment by jesusignazio** [comment]
Something like this:

![photo_2019-08-08_11-21-37](https://user-images.githubusercontent.com/6038843/62890335-9a423700-bd43-11e9-9097-ccdd98d2e518.jpg)

**Comment by Jonasbeavis** [comment]
Many thx :)
