### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by Frenzis78** [Gameboypi/SPW#28]
Thank you for this incredible job. I managed to build it and make it work nearly in one shot. My only issue is that I'm completely new to raspberry pi and emulation and I thought your image contained the emulators and games...but it's empty. Can someone direct me on some source to help me out? Thank you.

**Comment by Jonasbeavis** [comment]
hi , send me your email. :)

**Comment by Frenzis78** [comment]
Hi, thanks for the reply, you can mail me here: kurtb73@hotmail.com . Thanks for the help
