### ISSUE TITLE
PCB dimension on JCLPCB

### ISSUE THREAD

**Issue by Frenzis78** [Gameboypi/SPW#29]
Hi, 
I'm going to order a new pcb, what dimension should I input, or does it even matter what I input on the JCLPCB website? I mesured the pcb, but in the geber file there is the screen adapter...

Any hint? Thank you

F.

**Comment by derekantrican** [comment]
The first image [here](https://github.com/Gameboypi/SPW/tree/master/Gerber%20files) shows the necessary inputs on JCLPCB

**Comment by Frenzis78** [comment]
oh dear... I must be blind... dam sorry and thanks for the help
