### ISSUE TITLE
3.5inch 54pin

### ISSUE THREAD

**Issue by HFx6** [Gameboypi/SPW#38]
assuming I can match the 8 used pins with the 54 available in this https://bit.ly/37ayUwO screen, would it still work

**Comment by Gameboypi** [comment]
In my experience, not possible

**Comment by HFx6** [comment]
what was the limiting factor for this not be possible? since I cant find any 18 pin 3.5inch displays

**Comment by bademux** [comment]
Hello,
Here is adapter https://github.com/mattc74/DPI-Pi
The discussion https://sudomod.com/forum/viewtopic.php?t=4381
Through motherboard should be reworked hard.
