### ISSUE TITLE
Is there possible to add a headphone output inside?

### ISSUE THREAD

**Issue by MestreALMO** [Gameboypi/SPW#40]
I never messed around with eletronics so i don't know if this is something hard or simple, i really want to use my headphones with it if possible. How can I make this?

![image](https://user-images.githubusercontent.com/29152190/76169913-d1eb5300-615b-11ea-8687-2f405a985b1a.png)

**Comment by phillymadison** [comment]
I’m pretty sure it’s 100% possible. The easiest way would be to use Bluetooth head phones. If not try a micro usb head phone adapter and plug it into the micro usb hub from the pi. I’m not sure if there’s a way to solder a jack in there and have room. I’m sure someone else could comment about that.

**Comment by Gameboypi** [comment]
Technically yes, by cutting off the speaker traces and turning the traces to the headphone jack (with sense pin) and run wires from the headphone jack to the speaker because the i2s chip doesn't have a HS pin, so you need to do some wiring and im not sure if there is any free space for that.
