### ISSUE TITLE
Possible to add battery indicators LED's link in orginal sp?

### ISSUE THREAD

**Issue by Morpewpew** [Gameboypi/SPW#41]
I was wondering if it would be possible to install battery level/charge indicator LED's like in the original sp? I was planning on buying an ads1015 and using it to have the onscreen indicator, but I would like to be able to have LED ones as well if possible. In addition when buying the ads1015 should I get the one that Adafruit sells or will a cheaper one from AliExpress work? Any help would be appreciated.

**Comment by HFx6** [comment]
you could use the onboard zero power light.
