### ISSUE TITLE
White screen - another time

### ISSUE THREAD

**Issue by DroidHackTeam** [Gameboypi/SPW#44]
Hello, 

Same problem. White screen when i turn on the raspberry pi 0. Don't know why. Please help me. I attach some pictures for details.
![20200425_005201](https://user-images.githubusercontent.com/13727434/80242153-193b8d80-868f-11ea-9b2f-4cd6158c9d61.jpg)
![20200425_005227](https://user-images.githubusercontent.com/13727434/80242172-1e004180-868f-11ea-85de-5618aa60ceef.jpg)

**Comment by Gameboypi** [comment]
https://github.com/Gameboypi/SPW/blob/master/Screen%20troubleshooting/README.md
