### ISSUE TITLE
Where is DC-DC StepUp converter?

### ISSUE THREAD

**Issue by SozinovD** [Gameboypi/SPW#45]
Can you explain please how is raspberry being powered? I know that raspberry needs 5V input power, but thereis no converter in scema

**Comment by Gameboypi** [comment]
Hi
Sorry for the late reply, raspberry pi 0 can be powered with 3v also, so I’m using the battery to power the raspberry pi which is 3.7v

**Comment by SozinovD** [comment]
Hi! 
Great news! Thanks a lot, i didn't find information about this feachure in the Net. 
Good luck and thanks again for info!
