### ISSUE TITLE
Questions about Build

### ISSUE THREAD

**Issue by zarderxio** [Gameboypi/SPW#5]
Hi All, 2 questions: 

For the ADS1015 optional battery monitor, how does that get implemented?

The link port is tad expensive online, does it have a functional purpose besides filling space? 

Thanks!

**Comment by Gameboypi** [comment]
There are five pads behind the battery terminal for the ADS1015, maybe did not explain it yet.. But these links will help you.
https://sudomod.com/forum/viewtopic.php?f=42&t=4585&start=140

Battery monitor code
https://github.com/HoolyHoo/Mintybatterymonitor/blob/master/README.md

I use the link port with little modifications
as micro usb input you can ignore it if you want, it's optional

**Comment by Gameboypi** [comment]
That’s how to wiring ads1015 
Sorry for bad image i have no access right now to pc “add 10k ohm resistor to a0 “

https://imgur.com/gallery/Y3OOpzn

Unfortunately there’s no battery monitoring code yet for retropie 4.4...

**Comment by JayCanuck** [comment]
Thanks!
