### ISSUE TITLE
PCB Printing

### ISSUE THREAD

**Issue by Ayowyn** [Gameboypi/SPW#52]
I placed the order with JLCPCB and they informed me that they cannot import the Gerberx2 format. Is there a RS-274X version of the file or another recommended PCB printer which supports the extension?

Thank you for the help!

**Comment by ercan1441** [comment]
I recently ordered it too from JLCPCB, had no problems. Just upload the complete gerber.zip file and it should work without issues.

**Comment by Ayowyn** [comment]
Despite their warnings I just reuploaded the file and it worked in case anyone else had the same issue.
