### ISSUE TITLE
3.2 Screen Details/Link?

### ISSUE THREAD

**Issue by LeonVolta** [Gameboypi/SPW#6]
Wondering if it would be possible to have the Parts List updated with the option for the 3.2 screen from Aliexpress or whatever it may come from? Thanks.

**Comment by Gameboypi** [comment]
Done! , check out the wiki :D

**Comment by LeonVolta** [comment]
Thanks @Gameboypi!

Beautiful project you've got here by the way. Cleanest SP Pi Zero build I've seen and the originality of the design is really awesome. Ij ust ordered my PCB yesterday and looking forward to completing my own!
