### ISSUE TITLE
Charging board not working

### ISSUE THREAD

**Issue by Eilermoon** [Gameboypi/SPW#66]
Hi all! Hoping there are a few people following this.

I have everything wired up and should be ready to go. Powering the board via the Pi Zero's micro USB works correctly with the screen, but I can't seem to power the board via the USB-C port on my TP4056 Charging board - the LED on that board doesn't even light up. I've pretty much completed my build other than this - buttons, games and battery all work. It won't power on with just the USB-C plugged in though and the battery taken out. Did I fry this board somehow?

Any feedback would be very helpful! I have a SP charger port too but don't have a charger to test it yet - I'll update when I can try that as well. Some pics attached that might help

![PXL_20230415_174946292](https://user-images.githubusercontent.com/62626513/232245333-d1fc1144-02b5-473d-aef3-10edf3d092f0.jpg)
![PXL_20230415_174954065](https://user-images.githubusercontent.com/62626513/232245334-3c8fc579-9ef7-4dff-afc5-e02cc7a140a8.jpg)

**Comment by Eilermoon** [comment]
Just adding an update: My board works now, but I'm not clear on what the issue was previously. I have since soldered on a SP Charger, which worked correctly and lit the LED on the TP4056 board. I also tried a different plug and USB-C cable, which also worked in the USB-C port! 

I've assembled everything and it's working great - the battery charges and is functional without being plugged in. I'll post an update and close this issue once I'm sure the issue was just the voltage input of the USB-C I was using previously.

**Comment by maarten682** [comment]
Not sure if that was the case here for you but USB-PD sources do not work with these charging boards. You pretty much need good ol usb-a to c cables to make them go.

**Comment by Eilermoon** [comment]
> Not sure if that was the case here for you but USB-PD sources do not work with these charging boards. You pretty much need good ol usb-a to c cables to make them go.

TIL what USB-PD is. But yes, I think you hit the nail. I was using a USB-C -> USB-C cable inbto my laptop, then from a wall socket and still didn't work. Must be the cables. Although I've tried a few USB-A -> USB-C from an outlet that didn't work as well, must've been too low Output. Thanks for the info!

**Comment by maarten682** [comment]
Yup pretty much every usb-c port that outputs power needs to do a bit of handshaking before it starts sending out 5v.  These charging boards dont do any of that, they pretty much just rely on legacy usb that always provides 5v even if you stick a fork in there. Most (but as you found out not all) usb-a ports should be able to do that. Power can become an issue if you charge the battery and run your pi and screen all at full blast but sign of life should be possible from most sources (even ports on reasonably modern laptops), just your pi booting doesnt pull that much power.
