### ISSUE TITLE
PAM8403

### ISSUE THREAD

**Issue by BRaSSaS** [Gameboypi/SPW#9]
¿Por que no usar este amplificador?Es mucho mas económico que el de Adafruit, lo usan en muchos proyectos  de gameboy de rpi para sacar el sonido.

**Comment by Gameboypi** [comment]
Sí, es mucho más barato, pero la calidad del sonido es más barata que su precio que no vale la pena usar. "yo uso el traductor"

**Comment by BRaSSaS** [comment]
Sorry, i saw in some images of the project some stickers in Spanish, and as i read the comment that you did not speak English, i assumed you were Spanish, my mistake.
Anyway, thanks for the explanation.
